spring:
<<<<<<< HEAD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ZXY123456
    url:  jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120
=======
  profiles:
    active: dev
>>>>>>> ca76460b9e005cb8b9c256e8058f1a03483ca668
